# Generated by Django 5.1.6 on 2025-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='max_athletes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporttype',
            name='min_athletes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
